// Command portraits learns what every hero portrait looks like from an installed copy of
// Dota, and writes the answer into internal/screen as Go source.
//
// The pictures themselves never enter the repository: what is kept is a signature each, a
// handful of bytes that says what colours a portrait is made of. Run it with `make portraits`
// after a patch adds heroes or arcanas.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"gourdian/internal/install"
	"gourdian/internal/screen"
	"gourdian/internal/vpk"
)

// heroArt is where Dota keeps the portrait it draws for each hero in the bar along the top.
const heroArt = "panorama/images/heroes/npc_dota_hero_"

// variant matches the suffix Dota adds for an arcana, a persona or an alternate style. The
// portrait is different art; the hero behind it is the same.
var variant = regexp.MustCompile(`_(alt\d*|persona\d+)$`)

// notHeroes are entries under the hero art that aren't heroes anyone picks.
var notHeroes = []string{"npc_dota_hero_allied_coach", "npc_dota_hero_base", "npc_dota_hero_target_dummy"}

func main() {
	dota := flag.String("dota", "", "the Dota 2 folder; found automatically when empty")
	out := flag.String("out", filepath.Join("internal", "screen", "portraits.go"), "the Go file to write")
	flag.Parse()
	if err := run(*dota, *out); err != nil {
		fmt.Fprintln(os.Stderr, "portraits:", err)
		os.Exit(1)
	}
}

func run(dota, out string) error {
	if dota == "" {
		found := install.FindDota()
		if len(found) == 0 {
			return fmt.Errorf("no Dota 2 install found; pass -dota <the folder holding game/dota>")
		}
		dota = found[0]
	}
	pack := filepath.Join(dota, "game", "dota", "pak01_dir.vpk")
	archive, err := vpk.Open(pack)
	if err != nil {
		return err
	}
	entries := archive.Find(heroArt)
	if len(entries) == 0 {
		return fmt.Errorf("%s holds no hero portraits", pack)
	}

	art := map[string][]string{}
	skipped := 0
	for _, e := range entries {
		name := strings.TrimSuffix(filepath.Base(e.Path), ".vtex_c")
		// Dota compiles each picture from a .png or a .psd and keeps the source's name.
		name = strings.TrimSuffix(strings.TrimSuffix(name, "_png"), "_psd")
		hero := variant.ReplaceAllString(name, "")
		if slices.Contains(notHeroes, hero) {
			continue
		}
		raw, err := archive.Read(e)
		if err != nil {
			return err
		}
		img, err := vpk.Texture(raw)
		if err != nil {
			// A portrait in a format this doesn't read is one hero the screen can't name,
			// not a reason to write nothing at all.
			fmt.Fprintf(os.Stderr, "portraits: skipping %s: %v\n", name, err)
			skipped++
			continue
		}
		sig := screen.Of(img, img.Bounds())
		text, err := sig.MarshalText()
		if err != nil {
			return err
		}
		art[hero] = append(art[hero], string(text))
	}
	if len(art) == 0 {
		return fmt.Errorf("no portrait in %s could be read", pack)
	}

	source, err := render(art, countAll(art))
	if err != nil {
		return err
	}
	if err := os.WriteFile(out, source, 0o644); err != nil {
		return err
	}
	fmt.Printf("portraits: %d heroes, %d portraits with their variants, from %s\n", len(art), countAll(art), dota)
	if skipped > 0 {
		fmt.Printf("portraits: %d could not be read\n", skipped)
	}
	return nil
}

func countAll(art map[string][]string) int {
	n := 0
	for _, sigs := range art {
		n += len(sigs)
	}
	return n
}

func render(art map[string][]string, total int) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/portraits; DO NOT EDIT.\n\n")
	b.WriteString("package screen\n\n")
	b.WriteString("// portraitArt is what every portrait Dota draws for a hero looks like, read from the\n")
	b.WriteString("// game's own files: the base art, and the arcana, persona and alternate styles that\n")
	b.WriteString("// never reach the web, each filed under the hero it really is. Keyed by the hero's\n")
	b.WriteString("// script name, which is how both the game state and OpenDota spell it.\n")
	b.WriteString(fmt.Sprintf("//\n// %d portraits of %d heroes. Run `make portraits` after a patch to bring it up to date.\n", total, len(art)))
	b.WriteString("var portraitArt = map[string][]string{\n")
	heroes := make([]string, 0, len(art))
	for hero := range art {
		heroes = append(heroes, hero)
	}
	sort.Strings(heroes)
	for _, hero := range heroes {
		sigs := art[hero]
		sort.Strings(sigs)
		b.WriteString(fmt.Sprintf("\t%q: {\n", hero))
		for _, s := range sigs {
			b.WriteString(fmt.Sprintf("\t\t%q,\n", s))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return format.Source([]byte(b.String()))
}
