package screen

import (
	"strings"
	"sync"
)

// Known is the signature of every portrait Dota draws for a hero, by the hero's script name,
// built once from the generated table. A hero has more than one when they have an arcana, a
// persona or an alternate style: different art, same hero.
func Known() map[string][]Signature {
	knownOnce.Do(func() {
		known = make(map[string][]Signature, len(portraitArt))
		for hero, art := range portraitArt {
			for _, text := range art {
				var s Signature
				if err := s.UnmarshalText([]byte(text)); err != nil {
					continue // generated by cmd/portraits, so this can only be a bad edit
				}
				known[hero] = append(known[hero], s)
			}
		}
	})
	return known
}

var (
	knownOnce sync.Once
	known     map[string][]Signature
)

// TableFor turns the portraits into a lookup by hero id, given how the caller numbers heroes.
// Heroes the caller doesn't name are left out, so a portrait for a hero the trainer has never
// heard of can't be read as anything.
func TableFor(ids map[string]int) Table {
	t := Table{}
	for hero, sigs := range Known() {
		id, ok := ids[hero]
		if !ok {
			// GSI and OpenDota both spell heroes npc_dota_hero_x, but be forgiving about a
			// caller that drops the prefix.
			if id, ok = ids[strings.TrimPrefix(hero, "npc_dota_hero_")]; !ok {
				continue
			}
		}
		for _, s := range sigs {
			t.add(id, s)
		}
	}
	return t
}
