package rules

import "gourdian/internal/coaching/coach"

// Templates are starting points in the rule editor.
var Templates = []coach.RuleSpec{
	{Name: "Save for BKB", Category: "items", Match: "all",
		When: coach.Trigger{Type: coach.WhenState, For: 5},
		If: []coach.Cond{
			{Field: "clock", Op: "ge", Num: 900},
			{Field: "gold", Op: "ge", Num: 4050},
			{Field: "has_item", Arg: "black_king_bar", Op: "false"},
		},
		Then:     coach.AlertSpec{Text: "You have {gold} gold: buy {item_name:black_king_bar}", Speech: "Buy B K B", Severity: "warn"},
		Cooldown: 60, Roles: []string{"carry", "mid"}},
	{Name: "Use Magic Wand when low", Category: "survival", Match: "all",
		When: coach.Trigger{Type: coach.WhenState, For: 1},
		If: []coach.Cond{
			{Field: "hp_pct", Op: "le", Num: 35},
			{Field: "item_ready", Arg: "magic_wand", Op: "true"},
			{Field: "item_charges", Arg: "magic_wand", Op: "ge", Num: 8},
		},
		Then:     coach.AlertSpec{Text: "{hp_pct}% HP: use your wand ({item_charges:magic_wand} charges)", Speech: "Use wand", Severity: "urgent"},
		Cooldown: 20},
	{Name: "Low mana", Category: "survival", Match: "all",
		When:     coach.Trigger{Type: coach.WhenChange},
		If:       []coach.Cond{{Field: "mana_pct", Op: "lt", Num: 20}, {Field: "alive", Op: "true"}},
		Then:     coach.AlertSpec{Text: "Mana at {mana_pct}%. Regen before you fight", Severity: "info", Silent: true},
		Cooldown: 60},
	{Name: "Lotus pool", Category: "timing", Match: "all",
		When: coach.Trigger{Type: coach.WhenSchedule, First: 180, Every: 180, Lead: 15, Until: 1800},
		Then: coach.AlertSpec{Text: "Lotus orbs at {at}, in {in}s", Speech: "Lotus in {in} seconds", Severity: "info"}},
	{Name: "Night falls", Category: "timing", Match: "all",
		When: coach.Trigger{Type: coach.WhenSchedule, First: 300, Every: 600, Lead: 15},
		Then: coach.AlertSpec{Text: "Night falls in {in}s ({at}). Vision shortens for both sides: ward, group up or back off",
			Speech: "Night in {in} seconds", Severity: "info"}},
	{Name: "Shop while dead", Category: "economy", Match: "all",
		When: coach.Trigger{Type: coach.WhenEvent, Event: "died"},
		If:   []coach.Cond{{Field: "gold", Op: "ge", Num: 600}},
		Then: coach.AlertSpec{Text: "Dead for {respawn}s with {gold} gold. Buy now, before it's lost", Speech: "Spend your gold", Severity: "warn", Mistake: false}},
	{Name: "Ultimate is up", Category: "skills", Match: "all",
		When: coach.Trigger{Type: coach.WhenChange},
		If:   []coach.Cond{{Field: "ultimate_ready", Op: "true"}, {Field: "level", Op: "ge", Num: 6}, {Field: "alive", Op: "true"}},
		Then: coach.AlertSpec{Text: "Your ultimate is ready. Look for a fight with your team", Speech: "Ultimate ready", Severity: "info"}},
	{Name: "Unspent talent", Category: "skills", Match: "all",
		When:     coach.Trigger{Type: coach.WhenState, For: 20},
		If:       []coach.Cond{{Field: "talent_points", Op: "ge", Num: 1}},
		Then:     coach.AlertSpec{Text: "Your level {talent_level} talent is unspent. Take one from the talent tree", Speech: "Take your level {talent_level} talent", Severity: "warn", Mistake: true, Advice: "Talents are free power and cost nothing but a click."},
		Cooldown: 60},
	{Name: "Idle in base", Category: "map", Match: "all",
		When:     coach.Trigger{Type: coach.WhenState, For: 20},
		If:       []coach.Cond{{Field: "near_fountain", Op: "true"}, {Field: "hp_pct", Op: "ge", Num: 90}, {Field: "clock", Op: "ge", Num: 60}},
		Then:     coach.AlertSpec{Text: "Still in base at full health. Get back out", Severity: "warn", Mistake: true, Advice: "Leave base as soon as you're healed."},
		Cooldown: 90},
}
